let challenge = 'I Love Days Of JavaScript';
console.log(challenge);
console.log(challenge.length);
let  challengeUp = challenge.toUpperCase();
console.log(challengeUp);
let challengeLow = challenge.toLowerCase();   
console.log(challengeLow);
let slice = challenge.substring(0,1);
console.log(slice);
let half_phrase = challenge.substring(0,7);
console.log(half_phrase);
let half2_phrase = challenge.substring(7);
console.log(half2_phrase);
let checking = challenge.includes('Script');
console.log(checking);
let challengeSplit = challenge.split(' ');
console.log(challengeSplit);
let logos = 'Facebook, Google, Microsoft, Apple, IBM, Oracle, Amazon';
logos = logos.split(',');
console.log(logos);
let challengePython = challenge.replace('JavaScript', 'Python');
console.log(challengePython);
let char15 = challenge.charAt(15);
console.log(char15)
let aFirstPosi = challenge.indexOf('a');
console.log(aFirstPosi);
let aLastPosi = challenge.lastIndexOf('a');
console.log(aLastPosi);
let exercise17 = 'You cannot end a sentence with because because because is a conjunction';
let exercise17Indexof = exercise17.indexOf('because');
console.log(exercise17Indexof);
let exercise17lastIndex = exercise17.lastIndexOf('because');
console.log(exercise17lastIndex);
let exercise17search = exercise17.search('because');
let challengeTrim = ' I Love Days Of JavaScript ';
console.log(challengeTrim.trim());
let challengeStart = challenge.startsWith("I");
console.log(challengeStart);
let challengeEnd = challenge.endsWith("JavaScript");
console.log(challengeEnd);
let challengeMatch = challenge.match('a');
console.log(challengeMatch);
let challengeConcat = half_phrase.concat(half2_phrase);
console.log(challengeConcat);
let challenge2 = challenge.repeat(2)
console.log(challenge2);